### PR TITLE
Added manpage.

### PR DESCRIPTION
**Pull request by jsbackus**
Please consider adding a man page for luap. I made a first pass. Please review to make sure I have the details correct.

### CODE REVIEW

**Comment by dpapavas** [comment]
Thanks for submitting a man page draft!  I cherry-picked your file into the wip branch and did some further editing.  If it's not too much trouble, see commit bcbe911189a6be5c13e8dce5f908d51340ec37f0 in the wip branch and let me know if you spot anything wrong with it.

Now of course the real problem is how to deploy this manpage.  Luarocks doesn't seem to support it, at least not directly, as far as I could see.

**Comment by jsbackus** [comment]
Sorry for the delay! Manpage looks good.

Agreed. I tried looking through the Luarocks docs and didn't see anything helpful. So... how do you feel about Makefiles? :smile: I can take a stab at one when I have a moment, if you'd like.

**Comment by dpapavas** [comment]
I did use Makefiles before porting to LuaRocks and I tried going with Makefile-based building with LuaRocks too.  From what I remember, the problem with Makefiles is that you have to manually sort out this mess that is Lua library naming.  Every distro seems to name their libraries in a different way.  Some use liblua.so for the latest version and liblua-5.x.so for previous versions, some always name them liblua-5.x.so and others will probably use liblua5.x.so.

I did manage to put together some sort of logic, to try to figure out which library to use, based on the version configured in LuaRocks.  It worked for me but, seeing as I couldn't test it on all major distros, I opted to go with LuaRocks' internal building mechanism.

Still given the other problem I have, that of installing side-by-side versions of luap for different Lua version, perhaps it's worth giving it another shot.  Feel free to look into it too, if you have the time.  You can find the last version of the Makefile [here](https://github.com/dpapavas/luaprompt/blob/2b6eddb7edf52845046f5530502cfd6e81674a74/Makefile), to use as a starting point.  I'll have a look to and we can compare notes.

One thing you're going to come up against from the start, is getting LuaRocks' configured version, which LuaRocks isn't kind enough to share with us.  The best way I've found to handle that, is to use the lua binary which LR does give you and parse the version with something like:

    lua -v 2>&1 | cut -c 5-7

**Comment by dpapavas** [comment]
Well, I did put a makefile together, but I don't think it's going to help us, as Hisham explains in [this list thread](http://sourceforge.net/p/luarocks/mailman/message/34386465/).

**Comment by jsbackus** [comment]
Argh! Yeah, it looks like LR is going to be less than helpful.

Nice Makefile. It would be helpful if it was part of the package. I'm not using LR in the Fedora package. I can't tell if it isn't allowed or just isn't done, so I put the build steps into the spec (which is [here](https://jsbackus.fedorapeople.org/lua-luaprompt/lua-luaprompt.spec), by the way). Might be worth having a Makefile that plays nice with LR but also can be used to install non-LR-related files, such as the manpage.

**Comment by dpapavas** [comment]
I don't see much of a point in using the Makefile with LR, if I'm going to have exactly the same functionality, as with a built-in method, with probably more headache.  At least not for now.  I might switch to makefile-based building in LR later, if it turns out that maintaining both a makefile and the LR built-in build is a pain.

I was hoping I might, at least, be allowed to install multiple versions of luap side-by-side, named `luap-5.2`, `luap-5.3` and so on and have a `luap` symlink, but that doesn't work either.  The makefile can do it alright but it places the link in the sandbox and then when LR copies it into place, it copies the target.

I'm going to keep the makefile as a stand-alone alternative to building via LR for anyone who likes (or needs) to compile the sources themselves.  It can then properly install the sources and create symlinks and such.

**Comment by jsbackus** [comment]
Agreed. I started on a Makefile that could be used with LR or stand-alone and it quickly became tedious. Using the Makefile as a complete alternative is a good idea and would be quite helpful. It's a shame that LR doesn't have more support for Lua-based utilities, but I guess the focus is still on Lua-as-an-extension-language.

Versioned script names is a good idea, particularly given the general need to keep multiple Lua versions around.

**Comment by dpapavas** [comment]
I finally added the Makefile.  You can find it [here](https://github.com/dpapavas/luaprompt/commit/6d2a28f25b5fc78daae969e3a63646c2a4585911), in case you want to take a look at it, or try it out.  I'll be making a new release in the next days.   Let me know if you find anything wrong with the Makefile.

**Comment by jsbackus** [comment]
Looks good to me. Was able to update the package spec file without a problem. Thanks!

**Pull request closed without merging**
